//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAS_DOCENTE
    {
        public string ID_DOCENTE { get; set; }
        public string APELLIDO_PATERNO_DOCENTE { get; set; }
        public string APELLIDO_MATERNO_DOCENTE { get; set; }
        public string PRIMER_NOMBRE_DOCENTE { get; set; }
        public string SEGUNDO_NOMBRE_DOCENTE { get; set; }
        public Nullable<System.DateTime> FECHA_NACIMIENTO_DOCENTE { get; set; }
        public Nullable<int> ID_ESTADO_CIVIL { get; set; }
        public Nullable<int> ID_PROVINCIA { get; set; }
        public string DIRECCION { get; set; }
        public string TELEF_DOCENTE { get; set; }
        public string CEL_DOCENTE { get; set; }
        public string IMG_DOCENTE { get; set; }
        public string CORREO_DOCENTE { get; set; }
        public Nullable<System.DateTime> FECHA_INGRESO_DOCENTE { get; set; }
    }
}
