//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Data
{
    using System;
    
    public partial class ObtenerIntervaloDetalleSedeCarrera_Result
    {
        public int ID_INTERVALO_DETALLE { get; set; }
        public Nullable<int> ID_INTERVALO { get; set; }
        public Nullable<System.TimeSpan> INICIO_INTERVALO { get; set; }
        public Nullable<System.TimeSpan> FIN_INTERVALO { get; set; }
        public string INTERVALO { get; set; }
    }
}
