//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Data
{
    using System;
    
    public partial class ObtenerEstudianteNotaDetalleCarrera_Result
    {
        public int ID_ESTUDIANTE_NOTA { get; set; }
        public string DESCRIPCION_PONDERACION { get; set; }
        public Nullable<decimal> VALOR_NOTA { get; set; }
        public Nullable<decimal> NOTA { get; set; }
    }
}
