//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Data
{
    using System;
    
    public partial class InscripcionDetalleCarrera_Result
    {
        public int ID_INSCRIP_DETALLE_CARRERA { get; set; }
        public string DESCRIPCION_PERIODO { get; set; }
        public Nullable<int> ESTADO { get; set; }
        public string DESCRIPCION_UNIVERSIDAD { get; set; }
        public string DESCRIPCION_CARRERA { get; set; }
        public string DESCRIPCION_INTERVALO { get; set; }
        public string HORA { get; set; }
        public string DESCRIPCION_PARALELO { get; set; }
        public int ID_INSCRIPCION_ESTADO { get; set; }
        public string DESCRIPCION_ESTADO { get; set; }
        public string DESCRIPCION_TIPO_PAGO { get; set; }
        public string NUMERO_FACTURA { get; set; }
    }
}
