//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAS_RESPUESTA_ENCUESTA_DOCENTE
    {
        public int ID_ENCUESTA_RESPUESTA { get; set; }
        public Nullable<int> ID_ENCUESTA_PREGUNTA { get; set; }
        public string ID_ESTUDIANTE { get; set; }
        public string ID_DOCENTE { get; set; }
        public Nullable<int> ID_CARRERA { get; set; }
        public Nullable<int> ID_MATERIA { get; set; }
        public Nullable<int> ID_INTERVALO_DETALLE { get; set; }
        public Nullable<int> ID_PARALELO { get; set; }
        public Nullable<int> VALOR_RESPUESTA { get; set; }
    }
}
