//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAS_UBICACION
    {
        public int UBI_ID { get; set; }
        public Nullable<int> PAIS_ID { get; set; }
        public string UBI_CIUDAD { get; set; }
        public string UBI_PROVINCIA { get; set; }
        public string UBI_CANTON { get; set; }
    }
}
