//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAS_HORARIO_DETALLE
    {
        public int ID_HORARIO_DETALLE { get; set; }
        public Nullable<int> ID_PARALELO_MATERIA { get; set; }
        public Nullable<int> ID_HORARIO { get; set; }
        public Nullable<int> ID_PERIODO { get; set; }
    }
}
