//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CAS_DataEntities : DbContext
    {
        public CAS_DataEntities()
            : base("name=CAS_DataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AUX_ABREVIATURA_DIA> AUX_ABREVIATURA_DIA { get; set; }
        public virtual DbSet<CAS_ASISTENCIA> CAS_ASISTENCIA { get; set; }
        public virtual DbSet<CAS_AUDITORIA> CAS_AUDITORIA { get; set; }
        public virtual DbSet<CAS_CARPETA_ADJUNTOS> CAS_CARPETA_ADJUNTOS { get; set; }
        public virtual DbSet<CAS_CARRERA> CAS_CARRERA { get; set; }
        public virtual DbSet<CAS_CARRERA_NOTA> CAS_CARRERA_NOTA { get; set; }
        public virtual DbSet<CAS_CARRERA_REQUISITOS> CAS_CARRERA_REQUISITOS { get; set; }
        public virtual DbSet<CAS_CRONOGRAMA> CAS_CRONOGRAMA { get; set; }
        public virtual DbSet<CAS_CRONOGRAMA_ADJUNTO> CAS_CRONOGRAMA_ADJUNTO { get; set; }
        public virtual DbSet<CAS_CRONOGRAMA_DETALLE> CAS_CRONOGRAMA_DETALLE { get; set; }
        public virtual DbSet<CAS_DIAS> CAS_DIAS { get; set; }
        public virtual DbSet<CAS_DOCENTE> CAS_DOCENTE { get; set; }
        public virtual DbSet<CAS_DOCENTE_NOTAS> CAS_DOCENTE_NOTAS { get; set; }
        public virtual DbSet<CAS_ESTADO_CIVIL> CAS_ESTADO_CIVIL { get; set; }
        public virtual DbSet<CAS_ESTUDIANTE> CAS_ESTUDIANTE { get; set; }
        public virtual DbSet<CAS_ESTUDIANTE_DETALLE> CAS_ESTUDIANTE_DETALLE { get; set; }
        public virtual DbSet<CAS_ESTUDIANTE_NOTA> CAS_ESTUDIANTE_NOTA { get; set; }
        public virtual DbSet<CAS_GRUPO> CAS_GRUPO { get; set; }
        public virtual DbSet<CAS_HORARIO> CAS_HORARIO { get; set; }
        public virtual DbSet<CAS_HORARIO_DETALLE> CAS_HORARIO_DETALLE { get; set; }
        public virtual DbSet<CAS_HORARIO_TIPO> CAS_HORARIO_TIPO { get; set; }
        public virtual DbSet<CAS_INSCRIPCION_DETALLE_CARRERA> CAS_INSCRIPCION_DETALLE_CARRERA { get; set; }
        public virtual DbSet<CAS_INSCRIPCION_ESTADO> CAS_INSCRIPCION_ESTADO { get; set; }
        public virtual DbSet<CAS_INTERVALO> CAS_INTERVALO { get; set; }
        public virtual DbSet<CAS_INTERVALO_DETALLE> CAS_INTERVALO_DETALLE { get; set; }
        public virtual DbSet<CAS_MATERIA> CAS_MATERIA { get; set; }
        public virtual DbSet<CAS_MENU> CAS_MENU { get; set; }
        public virtual DbSet<CAS_NOTA> CAS_NOTA { get; set; }
        public virtual DbSet<CAS_NOTA_DETALLE> CAS_NOTA_DETALLE { get; set; }
        public virtual DbSet<CAS_NOTA_PONDERACION> CAS_NOTA_PONDERACION { get; set; }
        public virtual DbSet<CAS_NOTIFICACIONES> CAS_NOTIFICACIONES { get; set; }
        public virtual DbSet<CAS_PARALELO> CAS_PARALELO { get; set; }
        public virtual DbSet<CAS_PARALELO_MATERIA> CAS_PARALELO_MATERIA { get; set; }
        public virtual DbSet<CAS_PERIODO> CAS_PERIODO { get; set; }
        public virtual DbSet<CAS_PERSONAL> CAS_PERSONAL { get; set; }
        public virtual DbSet<CAS_ROL> CAS_ROL { get; set; }
        public virtual DbSet<CAS_ROL_MENU> CAS_ROL_MENU { get; set; }
        public virtual DbSet<CAS_SALON> CAS_SALON { get; set; }
        public virtual DbSet<CAS_SEDE> CAS_SEDE { get; set; }
        public virtual DbSet<CAS_SEMANA> CAS_SEMANA { get; set; }
        public virtual DbSet<CAS_TIPO_INVERTALO> CAS_TIPO_INVERTALO { get; set; }
        public virtual DbSet<CAS_TIPO_PAGO> CAS_TIPO_PAGO { get; set; }
        public virtual DbSet<CAS_UBICACION> CAS_UBICACION { get; set; }
        public virtual DbSet<CAS_UNIVERSIDAD> CAS_UNIVERSIDAD { get; set; }
        public virtual DbSet<CAS_USUARIO> CAS_USUARIO { get; set; }
        public virtual DbSet<CAS_USUARIO_ROL> CAS_USUARIO_ROL { get; set; }
        public virtual DbSet<CAS_VISITA> CAS_VISITA { get; set; }
        public virtual DbSet<CAS_DOCENTE_ASISTENCIA> CAS_DOCENTE_ASISTENCIA { get; set; }
        public virtual DbSet<CAS_ESTUDIANTE_ASISTENCIA> CAS_ESTUDIANTE_ASISTENCIA { get; set; }
        public virtual DbSet<CAS_INSCRIPCION_FECHA> CAS_INSCRIPCION_FECHA { get; set; }
        public virtual DbSet<CAS_DOCENTE_MATERIA_PARALELO> CAS_DOCENTE_MATERIA_PARALELO { get; set; }
        public virtual DbSet<CAS_GENERO> CAS_GENERO { get; set; }
        public virtual DbSet<CAS_DESTINATARIO> CAS_DESTINATARIO { get; set; }
        public virtual DbSet<CAS_INSCRIPCION> CAS_INSCRIPCION { get; set; }
        public virtual DbSet<CAS_ENCUESTA_PREGUNTAS> CAS_ENCUESTA_PREGUNTAS { get; set; }
        public virtual DbSet<CAS_RESPUESTA_ENCUESTA_DOCENTE> CAS_RESPUESTA_ENCUESTA_DOCENTE { get; set; }
        public virtual DbSet<CAS_ENCUESTA> CAS_ENCUESTA { get; set; }
        public virtual DbSet<CAS_ENCUESTA_OPCION> CAS_ENCUESTA_OPCION { get; set; }
        public virtual DbSet<CAS_OBSERVACION> CAS_OBSERVACION { get; set; }
        public virtual DbSet<CAS_EVENTO> CAS_EVENTO { get; set; }
        public virtual DbSet<CAS_EVENTO_HORA> CAS_EVENTO_HORA { get; set; }
        public virtual DbSet<CAS_EVENTO_REGISTRO> CAS_EVENTO_REGISTRO { get; set; }
        public virtual DbSet<CAS_EVENTO_REGISTRO_DETALLE> CAS_EVENTO_REGISTRO_DETALLE { get; set; }
        public virtual DbSet<CAS_TAREAS> CAS_TAREAS { get; set; }
        public virtual DbSet<CAS_TAREA_ADJUNTO> CAS_TAREA_ADJUNTO { get; set; }
        public virtual DbSet<CAS_ESTUDIANTE_TAREA> CAS_ESTUDIANTE_TAREA { get; set; }
    
        public virtual int SP_EstudianteNotaParcial(string iD_ESTUDIANTE, Nullable<int> iD_CARRERA, Nullable<int> iD_PERIODO, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_ESTUDIANTEParameter = iD_ESTUDIANTE != null ?
                new ObjectParameter("ID_ESTUDIANTE", iD_ESTUDIANTE) :
                new ObjectParameter("ID_ESTUDIANTE", typeof(string));
    
            var iD_CARRERAParameter = iD_CARRERA.HasValue ?
                new ObjectParameter("ID_CARRERA", iD_CARRERA) :
                new ObjectParameter("ID_CARRERA", typeof(int));
    
            var iD_PERIODOParameter = iD_PERIODO.HasValue ?
                new ObjectParameter("ID_PERIODO", iD_PERIODO) :
                new ObjectParameter("ID_PERIODO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EstudianteNotaParcial", iD_ESTUDIANTEParameter, iD_CARRERAParameter, iD_PERIODOParameter, outMensaje, outID);
        }
    
        public virtual int SP_EstudianteNotaDetalle(string iD_ESTUDIANTE, Nullable<int> iD_NOTA_DETALLE, Nullable<int> iD_PERIODO, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_ESTUDIANTEParameter = iD_ESTUDIANTE != null ?
                new ObjectParameter("ID_ESTUDIANTE", iD_ESTUDIANTE) :
                new ObjectParameter("ID_ESTUDIANTE", typeof(string));
    
            var iD_NOTA_DETALLEParameter = iD_NOTA_DETALLE.HasValue ?
                new ObjectParameter("ID_NOTA_DETALLE", iD_NOTA_DETALLE) :
                new ObjectParameter("ID_NOTA_DETALLE", typeof(int));
    
            var iD_PERIODOParameter = iD_PERIODO.HasValue ?
                new ObjectParameter("ID_PERIODO", iD_PERIODO) :
                new ObjectParameter("ID_PERIODO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EstudianteNotaDetalle", iD_ESTUDIANTEParameter, iD_NOTA_DETALLEParameter, iD_PERIODOParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<DocenteObtenerCarreraMateria_Result> SP_DocenteObtenerCarreraMateria(string iD_DOCENTE, Nullable<int> iD_PERIODO, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_DOCENTEParameter = iD_DOCENTE != null ?
                new ObjectParameter("ID_DOCENTE", iD_DOCENTE) :
                new ObjectParameter("ID_DOCENTE", typeof(string));
    
            var iD_PERIODOParameter = iD_PERIODO.HasValue ?
                new ObjectParameter("ID_PERIODO", iD_PERIODO) :
                new ObjectParameter("ID_PERIODO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DocenteObtenerCarreraMateria_Result>("SP_DocenteObtenerCarreraMateria", iD_DOCENTEParameter, iD_PERIODOParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<DocenteObtenerHorario_Result> SP_DocenteObtenerHorario(string iD_DOCENTE, Nullable<int> iD_PERIODO, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_DOCENTEParameter = iD_DOCENTE != null ?
                new ObjectParameter("ID_DOCENTE", iD_DOCENTE) :
                new ObjectParameter("ID_DOCENTE", typeof(string));
    
            var iD_PERIODOParameter = iD_PERIODO.HasValue ?
                new ObjectParameter("ID_PERIODO", iD_PERIODO) :
                new ObjectParameter("ID_PERIODO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DocenteObtenerHorario_Result>("SP_DocenteObtenerHorario", iD_DOCENTEParameter, iD_PERIODOParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<DocenteHorarioDiario_Result> SP_DocenteHorarioDiario(string iD_DOCENTE, Nullable<int> iD_PERIODO, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_DOCENTEParameter = iD_DOCENTE != null ?
                new ObjectParameter("ID_DOCENTE", iD_DOCENTE) :
                new ObjectParameter("ID_DOCENTE", typeof(string));
    
            var iD_PERIODOParameter = iD_PERIODO.HasValue ?
                new ObjectParameter("ID_PERIODO", iD_PERIODO) :
                new ObjectParameter("ID_PERIODO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DocenteHorarioDiario_Result>("SP_DocenteHorarioDiario", iD_DOCENTEParameter, iD_PERIODOParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<DocenteObtenerAsistenciaEstudiantes_Result> SP_DocenteObtenerAsistenciaEstudiantes(Nullable<int> iD_HORARIO_DETALLE, Nullable<int> iD_PERIODO, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_HORARIO_DETALLEParameter = iD_HORARIO_DETALLE.HasValue ?
                new ObjectParameter("ID_HORARIO_DETALLE", iD_HORARIO_DETALLE) :
                new ObjectParameter("ID_HORARIO_DETALLE", typeof(int));
    
            var iD_PERIODOParameter = iD_PERIODO.HasValue ?
                new ObjectParameter("ID_PERIODO", iD_PERIODO) :
                new ObjectParameter("ID_PERIODO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DocenteObtenerAsistenciaEstudiantes_Result>("SP_DocenteObtenerAsistenciaEstudiantes", iD_HORARIO_DETALLEParameter, iD_PERIODOParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<DocenteObtenerAsistencia_Result> SP_DocenteObtenerAsistencia(string iD_DOCENTE, Nullable<int> iD_PERIODO, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_DOCENTEParameter = iD_DOCENTE != null ?
                new ObjectParameter("ID_DOCENTE", iD_DOCENTE) :
                new ObjectParameter("ID_DOCENTE", typeof(string));
    
            var iD_PERIODOParameter = iD_PERIODO.HasValue ?
                new ObjectParameter("ID_PERIODO", iD_PERIODO) :
                new ObjectParameter("ID_PERIODO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DocenteObtenerAsistencia_Result>("SP_DocenteObtenerAsistencia", iD_DOCENTEParameter, iD_PERIODOParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<DocenteRepositorioCarpeta_Result> SP_DocenteRepositorioCarpeta(Nullable<int> iD_CARRERA, Nullable<int> sEMANA_CRONOGRAMA, Nullable<int> iD_CRONOGRAMA, Nullable<int> iD_PERIODO, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_CARRERAParameter = iD_CARRERA.HasValue ?
                new ObjectParameter("ID_CARRERA", iD_CARRERA) :
                new ObjectParameter("ID_CARRERA", typeof(int));
    
            var sEMANA_CRONOGRAMAParameter = sEMANA_CRONOGRAMA.HasValue ?
                new ObjectParameter("SEMANA_CRONOGRAMA", sEMANA_CRONOGRAMA) :
                new ObjectParameter("SEMANA_CRONOGRAMA", typeof(int));
    
            var iD_CRONOGRAMAParameter = iD_CRONOGRAMA.HasValue ?
                new ObjectParameter("ID_CRONOGRAMA", iD_CRONOGRAMA) :
                new ObjectParameter("ID_CRONOGRAMA", typeof(int));
    
            var iD_PERIODOParameter = iD_PERIODO.HasValue ?
                new ObjectParameter("ID_PERIODO", iD_PERIODO) :
                new ObjectParameter("ID_PERIODO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DocenteRepositorioCarpeta_Result>("SP_DocenteRepositorioCarpeta", iD_CARRERAParameter, sEMANA_CRONOGRAMAParameter, iD_CRONOGRAMAParameter, iD_PERIODOParameter, outMensaje, outID);
        }
    
        public virtual int SP_DocenteObtenerParciales(string iD_DOCENTE, Nullable<int> iD_SEDE, Nullable<int> iD_CARRERA, Nullable<int> iD_NOTA, Nullable<int> iD_PERIODO, Nullable<int> iD_INTERVALO_DETALLE, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_DOCENTEParameter = iD_DOCENTE != null ?
                new ObjectParameter("ID_DOCENTE", iD_DOCENTE) :
                new ObjectParameter("ID_DOCENTE", typeof(string));
    
            var iD_SEDEParameter = iD_SEDE.HasValue ?
                new ObjectParameter("ID_SEDE", iD_SEDE) :
                new ObjectParameter("ID_SEDE", typeof(int));
    
            var iD_CARRERAParameter = iD_CARRERA.HasValue ?
                new ObjectParameter("ID_CARRERA", iD_CARRERA) :
                new ObjectParameter("ID_CARRERA", typeof(int));
    
            var iD_NOTAParameter = iD_NOTA.HasValue ?
                new ObjectParameter("ID_NOTA", iD_NOTA) :
                new ObjectParameter("ID_NOTA", typeof(int));
    
            var iD_PERIODOParameter = iD_PERIODO.HasValue ?
                new ObjectParameter("ID_PERIODO", iD_PERIODO) :
                new ObjectParameter("ID_PERIODO", typeof(int));
    
            var iD_INTERVALO_DETALLEParameter = iD_INTERVALO_DETALLE.HasValue ?
                new ObjectParameter("ID_INTERVALO_DETALLE", iD_INTERVALO_DETALLE) :
                new ObjectParameter("ID_INTERVALO_DETALLE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_DocenteObtenerParciales", iD_DOCENTEParameter, iD_SEDEParameter, iD_CARRERAParameter, iD_NOTAParameter, iD_PERIODOParameter, iD_INTERVALO_DETALLEParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<DocenteObtenerEstudianteNota_Result> SP_DocenteObtenerEstudianteNota(string iD_DOCENTE, Nullable<int> iD_SEDE, Nullable<int> iD_CARRERA, Nullable<int> iD_NOTA, Nullable<int> iD_PERIODO, Nullable<int> iD_INTERVALO_DETALLE, Nullable<int> iD_NOTA_DETALLE, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_DOCENTEParameter = iD_DOCENTE != null ?
                new ObjectParameter("ID_DOCENTE", iD_DOCENTE) :
                new ObjectParameter("ID_DOCENTE", typeof(string));
    
            var iD_SEDEParameter = iD_SEDE.HasValue ?
                new ObjectParameter("ID_SEDE", iD_SEDE) :
                new ObjectParameter("ID_SEDE", typeof(int));
    
            var iD_CARRERAParameter = iD_CARRERA.HasValue ?
                new ObjectParameter("ID_CARRERA", iD_CARRERA) :
                new ObjectParameter("ID_CARRERA", typeof(int));
    
            var iD_NOTAParameter = iD_NOTA.HasValue ?
                new ObjectParameter("ID_NOTA", iD_NOTA) :
                new ObjectParameter("ID_NOTA", typeof(int));
    
            var iD_PERIODOParameter = iD_PERIODO.HasValue ?
                new ObjectParameter("ID_PERIODO", iD_PERIODO) :
                new ObjectParameter("ID_PERIODO", typeof(int));
    
            var iD_INTERVALO_DETALLEParameter = iD_INTERVALO_DETALLE.HasValue ?
                new ObjectParameter("ID_INTERVALO_DETALLE", iD_INTERVALO_DETALLE) :
                new ObjectParameter("ID_INTERVALO_DETALLE", typeof(int));
    
            var iD_NOTA_DETALLEParameter = iD_NOTA_DETALLE.HasValue ?
                new ObjectParameter("ID_NOTA_DETALLE", iD_NOTA_DETALLE) :
                new ObjectParameter("ID_NOTA_DETALLE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DocenteObtenerEstudianteNota_Result>("SP_DocenteObtenerEstudianteNota", iD_DOCENTEParameter, iD_SEDEParameter, iD_CARRERAParameter, iD_NOTAParameter, iD_PERIODOParameter, iD_INTERVALO_DETALLEParameter, iD_NOTA_DETALLEParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<DocenteObtenerEstudianteParcial_Result> SP_DocenteObtenerEstudianteParcial(Nullable<int> iD_SEDE, Nullable<int> iD_CARRERA, Nullable<int> iD_NOTA, Nullable<int> iD_PERIODO, Nullable<int> iD_INTERVALO_DETALLE, string iD_DOCENTE, string iD_ESTUDIANTE, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_SEDEParameter = iD_SEDE.HasValue ?
                new ObjectParameter("ID_SEDE", iD_SEDE) :
                new ObjectParameter("ID_SEDE", typeof(int));
    
            var iD_CARRERAParameter = iD_CARRERA.HasValue ?
                new ObjectParameter("ID_CARRERA", iD_CARRERA) :
                new ObjectParameter("ID_CARRERA", typeof(int));
    
            var iD_NOTAParameter = iD_NOTA.HasValue ?
                new ObjectParameter("ID_NOTA", iD_NOTA) :
                new ObjectParameter("ID_NOTA", typeof(int));
    
            var iD_PERIODOParameter = iD_PERIODO.HasValue ?
                new ObjectParameter("ID_PERIODO", iD_PERIODO) :
                new ObjectParameter("ID_PERIODO", typeof(int));
    
            var iD_INTERVALO_DETALLEParameter = iD_INTERVALO_DETALLE.HasValue ?
                new ObjectParameter("ID_INTERVALO_DETALLE", iD_INTERVALO_DETALLE) :
                new ObjectParameter("ID_INTERVALO_DETALLE", typeof(int));
    
            var iD_DOCENTEParameter = iD_DOCENTE != null ?
                new ObjectParameter("ID_DOCENTE", iD_DOCENTE) :
                new ObjectParameter("ID_DOCENTE", typeof(string));
    
            var iD_ESTUDIANTEParameter = iD_ESTUDIANTE != null ?
                new ObjectParameter("ID_ESTUDIANTE", iD_ESTUDIANTE) :
                new ObjectParameter("ID_ESTUDIANTE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DocenteObtenerEstudianteParcial_Result>("SP_DocenteObtenerEstudianteParcial", iD_SEDEParameter, iD_CARRERAParameter, iD_NOTAParameter, iD_PERIODOParameter, iD_INTERVALO_DETALLEParameter, iD_DOCENTEParameter, iD_ESTUDIANTEParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<DocenteObtenerEstudianteValor_Result> SP_DocenteObtenerEstudianteValor(Nullable<int> iD_SEDE, Nullable<int> iD_CARRERA, Nullable<int> iD_NOTA, Nullable<int> iD_PERIODO, Nullable<int> iD_INTERVALO_DETALLE, string iD_DOCENTE, string iD_ESTUDIANTE, Nullable<int> iD_NOTA_DETALLE, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_SEDEParameter = iD_SEDE.HasValue ?
                new ObjectParameter("ID_SEDE", iD_SEDE) :
                new ObjectParameter("ID_SEDE", typeof(int));
    
            var iD_CARRERAParameter = iD_CARRERA.HasValue ?
                new ObjectParameter("ID_CARRERA", iD_CARRERA) :
                new ObjectParameter("ID_CARRERA", typeof(int));
    
            var iD_NOTAParameter = iD_NOTA.HasValue ?
                new ObjectParameter("ID_NOTA", iD_NOTA) :
                new ObjectParameter("ID_NOTA", typeof(int));
    
            var iD_PERIODOParameter = iD_PERIODO.HasValue ?
                new ObjectParameter("ID_PERIODO", iD_PERIODO) :
                new ObjectParameter("ID_PERIODO", typeof(int));
    
            var iD_INTERVALO_DETALLEParameter = iD_INTERVALO_DETALLE.HasValue ?
                new ObjectParameter("ID_INTERVALO_DETALLE", iD_INTERVALO_DETALLE) :
                new ObjectParameter("ID_INTERVALO_DETALLE", typeof(int));
    
            var iD_DOCENTEParameter = iD_DOCENTE != null ?
                new ObjectParameter("ID_DOCENTE", iD_DOCENTE) :
                new ObjectParameter("ID_DOCENTE", typeof(string));
    
            var iD_ESTUDIANTEParameter = iD_ESTUDIANTE != null ?
                new ObjectParameter("ID_ESTUDIANTE", iD_ESTUDIANTE) :
                new ObjectParameter("ID_ESTUDIANTE", typeof(string));
    
            var iD_NOTA_DETALLEParameter = iD_NOTA_DETALLE.HasValue ?
                new ObjectParameter("ID_NOTA_DETALLE", iD_NOTA_DETALLE) :
                new ObjectParameter("ID_NOTA_DETALLE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DocenteObtenerEstudianteValor_Result>("SP_DocenteObtenerEstudianteValor", iD_SEDEParameter, iD_CARRERAParameter, iD_NOTAParameter, iD_PERIODOParameter, iD_INTERVALO_DETALLEParameter, iD_DOCENTEParameter, iD_ESTUDIANTEParameter, iD_NOTA_DETALLEParameter, outMensaje, outID);
        }
    
        public virtual int SP_NotificadorEnviaClave(string iD_USUARIO)
        {
            var iD_USUARIOParameter = iD_USUARIO != null ?
                new ObjectParameter("ID_USUARIO", iD_USUARIO) :
                new ObjectParameter("ID_USUARIO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_NotificadorEnviaClave", iD_USUARIOParameter);
        }
    
        public virtual ObjectResult<DocenteObtenerNotaParciales_Result> SP_DocenteObtenerNotaParciales(string iD_DOCENTE, Nullable<int> iD_SEDE, Nullable<int> iD_CARRERA, Nullable<int> iD_NOTA, Nullable<int> iD_PERIODO, Nullable<int> iD_INTERVALO_DETALLE, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_DOCENTEParameter = iD_DOCENTE != null ?
                new ObjectParameter("ID_DOCENTE", iD_DOCENTE) :
                new ObjectParameter("ID_DOCENTE", typeof(string));
    
            var iD_SEDEParameter = iD_SEDE.HasValue ?
                new ObjectParameter("ID_SEDE", iD_SEDE) :
                new ObjectParameter("ID_SEDE", typeof(int));
    
            var iD_CARRERAParameter = iD_CARRERA.HasValue ?
                new ObjectParameter("ID_CARRERA", iD_CARRERA) :
                new ObjectParameter("ID_CARRERA", typeof(int));
    
            var iD_NOTAParameter = iD_NOTA.HasValue ?
                new ObjectParameter("ID_NOTA", iD_NOTA) :
                new ObjectParameter("ID_NOTA", typeof(int));
    
            var iD_PERIODOParameter = iD_PERIODO.HasValue ?
                new ObjectParameter("ID_PERIODO", iD_PERIODO) :
                new ObjectParameter("ID_PERIODO", typeof(int));
    
            var iD_INTERVALO_DETALLEParameter = iD_INTERVALO_DETALLE.HasValue ?
                new ObjectParameter("ID_INTERVALO_DETALLE", iD_INTERVALO_DETALLE) :
                new ObjectParameter("ID_INTERVALO_DETALLE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DocenteObtenerNotaParciales_Result>("SP_DocenteObtenerNotaParciales", iD_DOCENTEParameter, iD_SEDEParameter, iD_CARRERAParameter, iD_NOTAParameter, iD_PERIODOParameter, iD_INTERVALO_DETALLEParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<DocenteObtenerNotaDetalle_Result> SP_DocenteObtenerNotaDetalle(string iD_DOCENTE, Nullable<int> iD_SEDE, Nullable<int> iD_CARRERA, Nullable<int> iD_NOTA, Nullable<int> iD_PERIODO, Nullable<int> iD_INTERVALO_DETALLE, Nullable<int> iD_NOTA_DETALLE, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_DOCENTEParameter = iD_DOCENTE != null ?
                new ObjectParameter("ID_DOCENTE", iD_DOCENTE) :
                new ObjectParameter("ID_DOCENTE", typeof(string));
    
            var iD_SEDEParameter = iD_SEDE.HasValue ?
                new ObjectParameter("ID_SEDE", iD_SEDE) :
                new ObjectParameter("ID_SEDE", typeof(int));
    
            var iD_CARRERAParameter = iD_CARRERA.HasValue ?
                new ObjectParameter("ID_CARRERA", iD_CARRERA) :
                new ObjectParameter("ID_CARRERA", typeof(int));
    
            var iD_NOTAParameter = iD_NOTA.HasValue ?
                new ObjectParameter("ID_NOTA", iD_NOTA) :
                new ObjectParameter("ID_NOTA", typeof(int));
    
            var iD_PERIODOParameter = iD_PERIODO.HasValue ?
                new ObjectParameter("ID_PERIODO", iD_PERIODO) :
                new ObjectParameter("ID_PERIODO", typeof(int));
    
            var iD_INTERVALO_DETALLEParameter = iD_INTERVALO_DETALLE.HasValue ?
                new ObjectParameter("ID_INTERVALO_DETALLE", iD_INTERVALO_DETALLE) :
                new ObjectParameter("ID_INTERVALO_DETALLE", typeof(int));
    
            var iD_NOTA_DETALLEParameter = iD_NOTA_DETALLE.HasValue ?
                new ObjectParameter("ID_NOTA_DETALLE", iD_NOTA_DETALLE) :
                new ObjectParameter("ID_NOTA_DETALLE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DocenteObtenerNotaDetalle_Result>("SP_DocenteObtenerNotaDetalle", iD_DOCENTEParameter, iD_SEDEParameter, iD_CARRERAParameter, iD_NOTAParameter, iD_PERIODOParameter, iD_INTERVALO_DETALLEParameter, iD_NOTA_DETALLEParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<DocenteObtenerNotaDetalleEstudiante_Result> SP_DocenteObtenerNotaDetalleEstudiante(string iD_DOCENTE, Nullable<int> iD_SEDE, Nullable<int> iD_CARRERA, Nullable<int> iD_NOTA, Nullable<int> iD_PERIODO, Nullable<int> iD_INTERVALO_DETALLE, string iD_ESTUDIANTE, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_DOCENTEParameter = iD_DOCENTE != null ?
                new ObjectParameter("ID_DOCENTE", iD_DOCENTE) :
                new ObjectParameter("ID_DOCENTE", typeof(string));
    
            var iD_SEDEParameter = iD_SEDE.HasValue ?
                new ObjectParameter("ID_SEDE", iD_SEDE) :
                new ObjectParameter("ID_SEDE", typeof(int));
    
            var iD_CARRERAParameter = iD_CARRERA.HasValue ?
                new ObjectParameter("ID_CARRERA", iD_CARRERA) :
                new ObjectParameter("ID_CARRERA", typeof(int));
    
            var iD_NOTAParameter = iD_NOTA.HasValue ?
                new ObjectParameter("ID_NOTA", iD_NOTA) :
                new ObjectParameter("ID_NOTA", typeof(int));
    
            var iD_PERIODOParameter = iD_PERIODO.HasValue ?
                new ObjectParameter("ID_PERIODO", iD_PERIODO) :
                new ObjectParameter("ID_PERIODO", typeof(int));
    
            var iD_INTERVALO_DETALLEParameter = iD_INTERVALO_DETALLE.HasValue ?
                new ObjectParameter("ID_INTERVALO_DETALLE", iD_INTERVALO_DETALLE) :
                new ObjectParameter("ID_INTERVALO_DETALLE", typeof(int));
    
            var iD_ESTUDIANTEParameter = iD_ESTUDIANTE != null ?
                new ObjectParameter("ID_ESTUDIANTE", iD_ESTUDIANTE) :
                new ObjectParameter("ID_ESTUDIANTE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DocenteObtenerNotaDetalleEstudiante_Result>("SP_DocenteObtenerNotaDetalleEstudiante", iD_DOCENTEParameter, iD_SEDEParameter, iD_CARRERAParameter, iD_NOTAParameter, iD_PERIODOParameter, iD_INTERVALO_DETALLEParameter, iD_ESTUDIANTEParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<DocenteObtenerNotaEstudiante_Result> SP_DocenteObtenerNotaEstudiante(string iD_DOCENTE, Nullable<int> iD_SEDE, Nullable<int> iD_CARRERA, Nullable<int> iD_NOTA, Nullable<int> iD_PERIODO, Nullable<int> iD_INTERVALO_DETALLE, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_DOCENTEParameter = iD_DOCENTE != null ?
                new ObjectParameter("ID_DOCENTE", iD_DOCENTE) :
                new ObjectParameter("ID_DOCENTE", typeof(string));
    
            var iD_SEDEParameter = iD_SEDE.HasValue ?
                new ObjectParameter("ID_SEDE", iD_SEDE) :
                new ObjectParameter("ID_SEDE", typeof(int));
    
            var iD_CARRERAParameter = iD_CARRERA.HasValue ?
                new ObjectParameter("ID_CARRERA", iD_CARRERA) :
                new ObjectParameter("ID_CARRERA", typeof(int));
    
            var iD_NOTAParameter = iD_NOTA.HasValue ?
                new ObjectParameter("ID_NOTA", iD_NOTA) :
                new ObjectParameter("ID_NOTA", typeof(int));
    
            var iD_PERIODOParameter = iD_PERIODO.HasValue ?
                new ObjectParameter("ID_PERIODO", iD_PERIODO) :
                new ObjectParameter("ID_PERIODO", typeof(int));
    
            var iD_INTERVALO_DETALLEParameter = iD_INTERVALO_DETALLE.HasValue ?
                new ObjectParameter("ID_INTERVALO_DETALLE", iD_INTERVALO_DETALLE) :
                new ObjectParameter("ID_INTERVALO_DETALLE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DocenteObtenerNotaEstudiante_Result>("SP_DocenteObtenerNotaEstudiante", iD_DOCENTEParameter, iD_SEDEParameter, iD_CARRERAParameter, iD_NOTAParameter, iD_PERIODOParameter, iD_INTERVALO_DETALLEParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<EstudianteRepositorioSemana_Result> SP_EstudianteRepositorioSemana(Nullable<int> iD_SEDE, Nullable<int> iD_CARRERA, Nullable<int> iD_PERIODO, Nullable<int> iD_TIPO_INTERVALO, Nullable<int> iD_PARALELO, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_SEDEParameter = iD_SEDE.HasValue ?
                new ObjectParameter("ID_SEDE", iD_SEDE) :
                new ObjectParameter("ID_SEDE", typeof(int));
    
            var iD_CARRERAParameter = iD_CARRERA.HasValue ?
                new ObjectParameter("ID_CARRERA", iD_CARRERA) :
                new ObjectParameter("ID_CARRERA", typeof(int));
    
            var iD_PERIODOParameter = iD_PERIODO.HasValue ?
                new ObjectParameter("ID_PERIODO", iD_PERIODO) :
                new ObjectParameter("ID_PERIODO", typeof(int));
    
            var iD_TIPO_INTERVALOParameter = iD_TIPO_INTERVALO.HasValue ?
                new ObjectParameter("ID_TIPO_INTERVALO", iD_TIPO_INTERVALO) :
                new ObjectParameter("ID_TIPO_INTERVALO", typeof(int));
    
            var iD_PARALELOParameter = iD_PARALELO.HasValue ?
                new ObjectParameter("ID_PARALELO", iD_PARALELO) :
                new ObjectParameter("ID_PARALELO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EstudianteRepositorioSemana_Result>("SP_EstudianteRepositorioSemana", iD_SEDEParameter, iD_CARRERAParameter, iD_PERIODOParameter, iD_TIPO_INTERVALOParameter, iD_PARALELOParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<EstudianteRepositorioCarpeta_Result> SP_EstudianteRepositorioCarpeta(Nullable<int> iD_CARRERA, Nullable<int> sEMANA_CRONOGRAMA, Nullable<int> iD_CRONOGRAMA, Nullable<int> iD_PERIODO, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_CARRERAParameter = iD_CARRERA.HasValue ?
                new ObjectParameter("ID_CARRERA", iD_CARRERA) :
                new ObjectParameter("ID_CARRERA", typeof(int));
    
            var sEMANA_CRONOGRAMAParameter = sEMANA_CRONOGRAMA.HasValue ?
                new ObjectParameter("SEMANA_CRONOGRAMA", sEMANA_CRONOGRAMA) :
                new ObjectParameter("SEMANA_CRONOGRAMA", typeof(int));
    
            var iD_CRONOGRAMAParameter = iD_CRONOGRAMA.HasValue ?
                new ObjectParameter("ID_CRONOGRAMA", iD_CRONOGRAMA) :
                new ObjectParameter("ID_CRONOGRAMA", typeof(int));
    
            var iD_PERIODOParameter = iD_PERIODO.HasValue ?
                new ObjectParameter("ID_PERIODO", iD_PERIODO) :
                new ObjectParameter("ID_PERIODO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EstudianteRepositorioCarpeta_Result>("SP_EstudianteRepositorioCarpeta", iD_CARRERAParameter, sEMANA_CRONOGRAMAParameter, iD_CRONOGRAMAParameter, iD_PERIODOParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<EstudianteObtenerCarreraMateria_Result> SP_EstudianteObtenerCarreraMateria(string iD_ESTUDIANTE, Nullable<int> iD_PERIODO, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_ESTUDIANTEParameter = iD_ESTUDIANTE != null ?
                new ObjectParameter("ID_ESTUDIANTE", iD_ESTUDIANTE) :
                new ObjectParameter("ID_ESTUDIANTE", typeof(string));
    
            var iD_PERIODOParameter = iD_PERIODO.HasValue ?
                new ObjectParameter("ID_PERIODO", iD_PERIODO) :
                new ObjectParameter("ID_PERIODO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EstudianteObtenerCarreraMateria_Result>("SP_EstudianteObtenerCarreraMateria", iD_ESTUDIANTEParameter, iD_PERIODOParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<EstudianteObtenerHorario_Result> SP_EstudianteObtenerHorario(string iD_ESTUDIANTE, Nullable<int> iD_PERIODO, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_ESTUDIANTEParameter = iD_ESTUDIANTE != null ?
                new ObjectParameter("ID_ESTUDIANTE", iD_ESTUDIANTE) :
                new ObjectParameter("ID_ESTUDIANTE", typeof(string));
    
            var iD_PERIODOParameter = iD_PERIODO.HasValue ?
                new ObjectParameter("ID_PERIODO", iD_PERIODO) :
                new ObjectParameter("ID_PERIODO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EstudianteObtenerHorario_Result>("SP_EstudianteObtenerHorario", iD_ESTUDIANTEParameter, iD_PERIODOParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<EstudianteObtenerAsistencia_Result> SP_EstudianteObtenerAsistencia(string iD_ESTUDIANTE, Nullable<int> iD_PERIODO, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_ESTUDIANTEParameter = iD_ESTUDIANTE != null ?
                new ObjectParameter("ID_ESTUDIANTE", iD_ESTUDIANTE) :
                new ObjectParameter("ID_ESTUDIANTE", typeof(string));
    
            var iD_PERIODOParameter = iD_PERIODO.HasValue ?
                new ObjectParameter("ID_PERIODO", iD_PERIODO) :
                new ObjectParameter("ID_PERIODO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EstudianteObtenerAsistencia_Result>("SP_EstudianteObtenerAsistencia", iD_ESTUDIANTEParameter, iD_PERIODOParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<EstudianteObtenerNotaParciales_Result> SP_EstudianteObtenerNotaParciales(Nullable<int> iD_CARRERA, Nullable<int> iD_TIPO_INTERVALO, Nullable<int> iD_PERIODO, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_CARRERAParameter = iD_CARRERA.HasValue ?
                new ObjectParameter("ID_CARRERA", iD_CARRERA) :
                new ObjectParameter("ID_CARRERA", typeof(int));
    
            var iD_TIPO_INTERVALOParameter = iD_TIPO_INTERVALO.HasValue ?
                new ObjectParameter("ID_TIPO_INTERVALO", iD_TIPO_INTERVALO) :
                new ObjectParameter("ID_TIPO_INTERVALO", typeof(int));
    
            var iD_PERIODOParameter = iD_PERIODO.HasValue ?
                new ObjectParameter("ID_PERIODO", iD_PERIODO) :
                new ObjectParameter("ID_PERIODO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EstudianteObtenerNotaParciales_Result>("SP_EstudianteObtenerNotaParciales", iD_CARRERAParameter, iD_TIPO_INTERVALOParameter, iD_PERIODOParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<EstudianteObtenerNotaDetalle_Result> SP_EstudianteObtenerNotaDetalle(Nullable<int> iD_NOTA_DETALLE, string iD_ESTUDIANTE, Nullable<int> iD_PERIODO, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_NOTA_DETALLEParameter = iD_NOTA_DETALLE.HasValue ?
                new ObjectParameter("ID_NOTA_DETALLE", iD_NOTA_DETALLE) :
                new ObjectParameter("ID_NOTA_DETALLE", typeof(int));
    
            var iD_ESTUDIANTEParameter = iD_ESTUDIANTE != null ?
                new ObjectParameter("ID_ESTUDIANTE", iD_ESTUDIANTE) :
                new ObjectParameter("ID_ESTUDIANTE", typeof(string));
    
            var iD_PERIODOParameter = iD_PERIODO.HasValue ?
                new ObjectParameter("ID_PERIODO", iD_PERIODO) :
                new ObjectParameter("ID_PERIODO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EstudianteObtenerNotaDetalle_Result>("SP_EstudianteObtenerNotaDetalle", iD_NOTA_DETALLEParameter, iD_ESTUDIANTEParameter, iD_PERIODOParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<EstudianteObtenerPromedio_Result> SP_EstudianteObtenerPromedio(string iD_ESTUDIANTE, Nullable<int> iD_PERIODO, Nullable<int> iD_CARRERA, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_ESTUDIANTEParameter = iD_ESTUDIANTE != null ?
                new ObjectParameter("ID_ESTUDIANTE", iD_ESTUDIANTE) :
                new ObjectParameter("ID_ESTUDIANTE", typeof(string));
    
            var iD_PERIODOParameter = iD_PERIODO.HasValue ?
                new ObjectParameter("ID_PERIODO", iD_PERIODO) :
                new ObjectParameter("ID_PERIODO", typeof(int));
    
            var iD_CARRERAParameter = iD_CARRERA.HasValue ?
                new ObjectParameter("ID_CARRERA", iD_CARRERA) :
                new ObjectParameter("ID_CARRERA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EstudianteObtenerPromedio_Result>("SP_EstudianteObtenerPromedio", iD_ESTUDIANTEParameter, iD_PERIODOParameter, iD_CARRERAParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<ObtenerCarreraValida_Result> SP_ObtenerCarreraValida(string iD_INSCRIP, Nullable<int> iD_PERIODO, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_INSCRIPParameter = iD_INSCRIP != null ?
                new ObjectParameter("ID_INSCRIP", iD_INSCRIP) :
                new ObjectParameter("ID_INSCRIP", typeof(string));
    
            var iD_PERIODOParameter = iD_PERIODO.HasValue ?
                new ObjectParameter("ID_PERIODO", iD_PERIODO) :
                new ObjectParameter("ID_PERIODO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerCarreraValida_Result>("SP_ObtenerCarreraValida", iD_INSCRIPParameter, iD_PERIODOParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<ObtenerIntervaloSedeCarrera_Result> SP_ObtenerIntervaloSedeCarrera(Nullable<int> iD_CARRERA, Nullable<int> iD_SEDE, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_CARRERAParameter = iD_CARRERA.HasValue ?
                new ObjectParameter("ID_CARRERA", iD_CARRERA) :
                new ObjectParameter("ID_CARRERA", typeof(int));
    
            var iD_SEDEParameter = iD_SEDE.HasValue ?
                new ObjectParameter("ID_SEDE", iD_SEDE) :
                new ObjectParameter("ID_SEDE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerIntervaloSedeCarrera_Result>("SP_ObtenerIntervaloSedeCarrera", iD_CARRERAParameter, iD_SEDEParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<ObtenerIntervaloDetalleSedeCarrera_Result> SP_ObtenerIntervaloDetalleSedeCarrera(Nullable<int> iD_CARRERA, Nullable<int> iD_SEDE, string iD_INSCRIP, Nullable<int> iD_INTERVALO, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_CARRERAParameter = iD_CARRERA.HasValue ?
                new ObjectParameter("ID_CARRERA", iD_CARRERA) :
                new ObjectParameter("ID_CARRERA", typeof(int));
    
            var iD_SEDEParameter = iD_SEDE.HasValue ?
                new ObjectParameter("ID_SEDE", iD_SEDE) :
                new ObjectParameter("ID_SEDE", typeof(int));
    
            var iD_INSCRIPParameter = iD_INSCRIP != null ?
                new ObjectParameter("ID_INSCRIP", iD_INSCRIP) :
                new ObjectParameter("ID_INSCRIP", typeof(string));
    
            var iD_INTERVALOParameter = iD_INTERVALO.HasValue ?
                new ObjectParameter("ID_INTERVALO", iD_INTERVALO) :
                new ObjectParameter("ID_INTERVALO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerIntervaloDetalleSedeCarrera_Result>("SP_ObtenerIntervaloDetalleSedeCarrera", iD_CARRERAParameter, iD_SEDEParameter, iD_INSCRIPParameter, iD_INTERVALOParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<ObtenerParaleloSedeCarrera_Result> SP_ObtenerParaleloSedeCarrera(Nullable<int> iD_CARRERA, Nullable<int> iD_SEDE, Nullable<int> iD_INTERVALO, Nullable<int> iD_INTERVALO_DETALLE, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_CARRERAParameter = iD_CARRERA.HasValue ?
                new ObjectParameter("ID_CARRERA", iD_CARRERA) :
                new ObjectParameter("ID_CARRERA", typeof(int));
    
            var iD_SEDEParameter = iD_SEDE.HasValue ?
                new ObjectParameter("ID_SEDE", iD_SEDE) :
                new ObjectParameter("ID_SEDE", typeof(int));
    
            var iD_INTERVALOParameter = iD_INTERVALO.HasValue ?
                new ObjectParameter("ID_INTERVALO", iD_INTERVALO) :
                new ObjectParameter("ID_INTERVALO", typeof(int));
    
            var iD_INTERVALO_DETALLEParameter = iD_INTERVALO_DETALLE.HasValue ?
                new ObjectParameter("ID_INTERVALO_DETALLE", iD_INTERVALO_DETALLE) :
                new ObjectParameter("ID_INTERVALO_DETALLE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerParaleloSedeCarrera_Result>("SP_ObtenerParaleloSedeCarrera", iD_CARRERAParameter, iD_SEDEParameter, iD_INTERVALOParameter, iD_INTERVALO_DETALLEParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<DocenteCarreraIntervalo_Result> SP_DocenteCarreraIntervalo(string iD_DOCENTE, Nullable<int> iD_PERIODO, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_DOCENTEParameter = iD_DOCENTE != null ?
                new ObjectParameter("ID_DOCENTE", iD_DOCENTE) :
                new ObjectParameter("ID_DOCENTE", typeof(string));
    
            var iD_PERIODOParameter = iD_PERIODO.HasValue ?
                new ObjectParameter("ID_PERIODO", iD_PERIODO) :
                new ObjectParameter("ID_PERIODO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DocenteCarreraIntervalo_Result>("SP_DocenteCarreraIntervalo", iD_DOCENTEParameter, iD_PERIODOParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<DocenteRepositorioSemana_Result> SP_DocenteRepositorioSemana(Nullable<int> iD_SEDE, Nullable<int> iD_CARRERA, Nullable<int> iD_PERIODO, Nullable<int> iD_TIPO_INTERVALO, Nullable<int> iD_PARALELO, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_SEDEParameter = iD_SEDE.HasValue ?
                new ObjectParameter("ID_SEDE", iD_SEDE) :
                new ObjectParameter("ID_SEDE", typeof(int));
    
            var iD_CARRERAParameter = iD_CARRERA.HasValue ?
                new ObjectParameter("ID_CARRERA", iD_CARRERA) :
                new ObjectParameter("ID_CARRERA", typeof(int));
    
            var iD_PERIODOParameter = iD_PERIODO.HasValue ?
                new ObjectParameter("ID_PERIODO", iD_PERIODO) :
                new ObjectParameter("ID_PERIODO", typeof(int));
    
            var iD_TIPO_INTERVALOParameter = iD_TIPO_INTERVALO.HasValue ?
                new ObjectParameter("ID_TIPO_INTERVALO", iD_TIPO_INTERVALO) :
                new ObjectParameter("ID_TIPO_INTERVALO", typeof(int));
    
            var iD_PARALELOParameter = iD_PARALELO.HasValue ?
                new ObjectParameter("ID_PARALELO", iD_PARALELO) :
                new ObjectParameter("ID_PARALELO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DocenteRepositorioSemana_Result>("SP_DocenteRepositorioSemana", iD_SEDEParameter, iD_CARRERAParameter, iD_PERIODOParameter, iD_TIPO_INTERVALOParameter, iD_PARALELOParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<ObtenerHorarioParalelo_Result> SP_ObtenerHorarioParalelo(Nullable<int> iD_PARALELO_MATERIA, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_PARALELO_MATERIAParameter = iD_PARALELO_MATERIA.HasValue ?
                new ObjectParameter("ID_PARALELO_MATERIA", iD_PARALELO_MATERIA) :
                new ObjectParameter("ID_PARALELO_MATERIA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerHorarioParalelo_Result>("SP_ObtenerHorarioParalelo", iD_PARALELO_MATERIAParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<ObtenerDocenteAsistencia_Result> SP_ObtenerDocenteAsistencia(string iD_DOCENTE, Nullable<int> iD_PERIODO, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_DOCENTEParameter = iD_DOCENTE != null ?
                new ObjectParameter("ID_DOCENTE", iD_DOCENTE) :
                new ObjectParameter("ID_DOCENTE", typeof(string));
    
            var iD_PERIODOParameter = iD_PERIODO.HasValue ?
                new ObjectParameter("ID_PERIODO", iD_PERIODO) :
                new ObjectParameter("ID_PERIODO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerDocenteAsistencia_Result>("SP_ObtenerDocenteAsistencia", iD_DOCENTEParameter, iD_PERIODOParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<Nullable<int>> SP_ActualizarDetalleNotas(Nullable<int> iD_INSCRIP_DETALLE_CARRERA, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_INSCRIP_DETALLE_CARRERAParameter = iD_INSCRIP_DETALLE_CARRERA.HasValue ?
                new ObjectParameter("ID_INSCRIP_DETALLE_CARRERA", iD_INSCRIP_DETALLE_CARRERA) :
                new ObjectParameter("ID_INSCRIP_DETALLE_CARRERA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_ActualizarDetalleNotas", iD_INSCRIP_DETALLE_CARRERAParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<ObtenerEstudianteNotaCarrera_Result> SP_ObtenerEstudianteNotaCarrera(Nullable<int> iD_INSCRIP_DETALLE_CARRERA, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_INSCRIP_DETALLE_CARRERAParameter = iD_INSCRIP_DETALLE_CARRERA.HasValue ?
                new ObjectParameter("ID_INSCRIP_DETALLE_CARRERA", iD_INSCRIP_DETALLE_CARRERA) :
                new ObjectParameter("ID_INSCRIP_DETALLE_CARRERA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerEstudianteNotaCarrera_Result>("SP_ObtenerEstudianteNotaCarrera", iD_INSCRIP_DETALLE_CARRERAParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<InscripcionDetalleCarrera_Result> SP_InscripcionDetalleCarrera(string iD_INSCRIP, Nullable<int> iD_INSCRIP_DETALLE_CARRERA, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_INSCRIPParameter = iD_INSCRIP != null ?
                new ObjectParameter("ID_INSCRIP", iD_INSCRIP) :
                new ObjectParameter("ID_INSCRIP", typeof(string));
    
            var iD_INSCRIP_DETALLE_CARRERAParameter = iD_INSCRIP_DETALLE_CARRERA.HasValue ?
                new ObjectParameter("ID_INSCRIP_DETALLE_CARRERA", iD_INSCRIP_DETALLE_CARRERA) :
                new ObjectParameter("ID_INSCRIP_DETALLE_CARRERA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<InscripcionDetalleCarrera_Result>("SP_InscripcionDetalleCarrera", iD_INSCRIPParameter, iD_INSCRIP_DETALLE_CARRERAParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<ObtenerEstudianteNotaDetalleCarrera_Result> SP_ObtenerEstudianteNotaDetalleCarrera(Nullable<int> iD_INSCRIP_DETALLE_CARRERA, Nullable<int> iD_NOTA_DETALLE, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_INSCRIP_DETALLE_CARRERAParameter = iD_INSCRIP_DETALLE_CARRERA.HasValue ?
                new ObjectParameter("ID_INSCRIP_DETALLE_CARRERA", iD_INSCRIP_DETALLE_CARRERA) :
                new ObjectParameter("ID_INSCRIP_DETALLE_CARRERA", typeof(int));
    
            var iD_NOTA_DETALLEParameter = iD_NOTA_DETALLE.HasValue ?
                new ObjectParameter("ID_NOTA_DETALLE", iD_NOTA_DETALLE) :
                new ObjectParameter("ID_NOTA_DETALLE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerEstudianteNotaDetalleCarrera_Result>("SP_ObtenerEstudianteNotaDetalleCarrera", iD_INSCRIP_DETALLE_CARRERAParameter, iD_NOTA_DETALLEParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<ObtenerEstudianteAsistenciaCarrera_Result> SP_ObtenerEstudianteAsistenciaCarrera(Nullable<int> iD_INSCRIP_DETALLE_CARRERA, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_INSCRIP_DETALLE_CARRERAParameter = iD_INSCRIP_DETALLE_CARRERA.HasValue ?
                new ObjectParameter("ID_INSCRIP_DETALLE_CARRERA", iD_INSCRIP_DETALLE_CARRERA) :
                new ObjectParameter("ID_INSCRIP_DETALLE_CARRERA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerEstudianteAsistenciaCarrera_Result>("SP_ObtenerEstudianteAsistenciaCarrera", iD_INSCRIP_DETALLE_CARRERAParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<DocenteObtenerDatosReporteDocente_Result> SP_DocenteObtenerDatosReporteDocente(Nullable<int> iD_SEDE, Nullable<int> iD_CARRERA, Nullable<int> iD_PERIODO, Nullable<int> iD_PARALELO, Nullable<int> iD_INTERVALO_DETALLE, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_SEDEParameter = iD_SEDE.HasValue ?
                new ObjectParameter("ID_SEDE", iD_SEDE) :
                new ObjectParameter("ID_SEDE", typeof(int));
    
            var iD_CARRERAParameter = iD_CARRERA.HasValue ?
                new ObjectParameter("ID_CARRERA", iD_CARRERA) :
                new ObjectParameter("ID_CARRERA", typeof(int));
    
            var iD_PERIODOParameter = iD_PERIODO.HasValue ?
                new ObjectParameter("ID_PERIODO", iD_PERIODO) :
                new ObjectParameter("ID_PERIODO", typeof(int));
    
            var iD_PARALELOParameter = iD_PARALELO.HasValue ?
                new ObjectParameter("ID_PARALELO", iD_PARALELO) :
                new ObjectParameter("ID_PARALELO", typeof(int));
    
            var iD_INTERVALO_DETALLEParameter = iD_INTERVALO_DETALLE.HasValue ?
                new ObjectParameter("ID_INTERVALO_DETALLE", iD_INTERVALO_DETALLE) :
                new ObjectParameter("ID_INTERVALO_DETALLE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DocenteObtenerDatosReporteDocente_Result>("SP_DocenteObtenerDatosReporteDocente", iD_SEDEParameter, iD_CARRERAParameter, iD_PERIODOParameter, iD_PARALELOParameter, iD_INTERVALO_DETALLEParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<DocenteDatosCarreraMateria_Result> SP_DocenteDatosCarreraMateria(string iD_DOCENTE, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_DOCENTEParameter = iD_DOCENTE != null ?
                new ObjectParameter("ID_DOCENTE", iD_DOCENTE) :
                new ObjectParameter("ID_DOCENTE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DocenteDatosCarreraMateria_Result>("SP_DocenteDatosCarreraMateria", iD_DOCENTEParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<DocenteDatosEncuestaRespuesta_Result> SP_DocenteDatosEncuestaRespuesta(string iD_DOCENTE, Nullable<int> iD_CARRERA, Nullable<int> iD_MATERIA, Nullable<int> iD_INTERVALO_DETALLE, Nullable<int> iD_PARALELO, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_DOCENTEParameter = iD_DOCENTE != null ?
                new ObjectParameter("ID_DOCENTE", iD_DOCENTE) :
                new ObjectParameter("ID_DOCENTE", typeof(string));
    
            var iD_CARRERAParameter = iD_CARRERA.HasValue ?
                new ObjectParameter("ID_CARRERA", iD_CARRERA) :
                new ObjectParameter("ID_CARRERA", typeof(int));
    
            var iD_MATERIAParameter = iD_MATERIA.HasValue ?
                new ObjectParameter("ID_MATERIA", iD_MATERIA) :
                new ObjectParameter("ID_MATERIA", typeof(int));
    
            var iD_INTERVALO_DETALLEParameter = iD_INTERVALO_DETALLE.HasValue ?
                new ObjectParameter("ID_INTERVALO_DETALLE", iD_INTERVALO_DETALLE) :
                new ObjectParameter("ID_INTERVALO_DETALLE", typeof(int));
    
            var iD_PARALELOParameter = iD_PARALELO.HasValue ?
                new ObjectParameter("ID_PARALELO", iD_PARALELO) :
                new ObjectParameter("ID_PARALELO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DocenteDatosEncuestaRespuesta_Result>("SP_DocenteDatosEncuestaRespuesta", iD_DOCENTEParameter, iD_CARRERAParameter, iD_MATERIAParameter, iD_INTERVALO_DETALLEParameter, iD_PARALELOParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<ObtenerHorarioMateria_Result> SP_ObtenerHorarioMateria(Nullable<int> iD_SEDE, Nullable<int> iD_CARRERA, Nullable<int> iD_MATERIA, Nullable<int> iD_PARALELO, Nullable<int> iD_INTERVALO, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_SEDEParameter = iD_SEDE.HasValue ?
                new ObjectParameter("ID_SEDE", iD_SEDE) :
                new ObjectParameter("ID_SEDE", typeof(int));
    
            var iD_CARRERAParameter = iD_CARRERA.HasValue ?
                new ObjectParameter("ID_CARRERA", iD_CARRERA) :
                new ObjectParameter("ID_CARRERA", typeof(int));
    
            var iD_MATERIAParameter = iD_MATERIA.HasValue ?
                new ObjectParameter("ID_MATERIA", iD_MATERIA) :
                new ObjectParameter("ID_MATERIA", typeof(int));
    
            var iD_PARALELOParameter = iD_PARALELO.HasValue ?
                new ObjectParameter("ID_PARALELO", iD_PARALELO) :
                new ObjectParameter("ID_PARALELO", typeof(int));
    
            var iD_INTERVALOParameter = iD_INTERVALO.HasValue ?
                new ObjectParameter("ID_INTERVALO", iD_INTERVALO) :
                new ObjectParameter("ID_INTERVALO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerHorarioMateria_Result>("SP_ObtenerHorarioMateria", iD_SEDEParameter, iD_CARRERAParameter, iD_MATERIAParameter, iD_PARALELOParameter, iD_INTERVALOParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<ObtenerDocenteAsignadoHorarioMateria_Result> SP_ObtenerDocenteAsignadoHorarioMateria(Nullable<int> iD_HORARIO_DETALLE, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_HORARIO_DETALLEParameter = iD_HORARIO_DETALLE.HasValue ?
                new ObjectParameter("ID_HORARIO_DETALLE", iD_HORARIO_DETALLE) :
                new ObjectParameter("ID_HORARIO_DETALLE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerDocenteAsignadoHorarioMateria_Result>("SP_ObtenerDocenteAsignadoHorarioMateria", iD_HORARIO_DETALLEParameter, outMensaje, outID);
        }
    
        public virtual int sp_GenerarDetalleCronograma_Intensivo(Nullable<System.DateTime> fECHA_INICIO, Nullable<System.DateTime> fECHA_FIN, Nullable<int> iD_CRONOGRAMA)
        {
            var fECHA_INICIOParameter = fECHA_INICIO.HasValue ?
                new ObjectParameter("FECHA_INICIO", fECHA_INICIO) :
                new ObjectParameter("FECHA_INICIO", typeof(System.DateTime));
    
            var fECHA_FINParameter = fECHA_FIN.HasValue ?
                new ObjectParameter("FECHA_FIN", fECHA_FIN) :
                new ObjectParameter("FECHA_FIN", typeof(System.DateTime));
    
            var iD_CRONOGRAMAParameter = iD_CRONOGRAMA.HasValue ?
                new ObjectParameter("ID_CRONOGRAMA", iD_CRONOGRAMA) :
                new ObjectParameter("ID_CRONOGRAMA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GenerarDetalleCronograma_Intensivo", fECHA_INICIOParameter, fECHA_FINParameter, iD_CRONOGRAMAParameter);
        }
    
        public virtual int sp_GenerarDetalleCronograma_Regular(Nullable<System.DateTime> fECHA_INICIO, Nullable<System.DateTime> fECHA_FIN, Nullable<int> iD_CRONOGRAMA)
        {
            var fECHA_INICIOParameter = fECHA_INICIO.HasValue ?
                new ObjectParameter("FECHA_INICIO", fECHA_INICIO) :
                new ObjectParameter("FECHA_INICIO", typeof(System.DateTime));
    
            var fECHA_FINParameter = fECHA_FIN.HasValue ?
                new ObjectParameter("FECHA_FIN", fECHA_FIN) :
                new ObjectParameter("FECHA_FIN", typeof(System.DateTime));
    
            var iD_CRONOGRAMAParameter = iD_CRONOGRAMA.HasValue ?
                new ObjectParameter("ID_CRONOGRAMA", iD_CRONOGRAMA) :
                new ObjectParameter("ID_CRONOGRAMA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GenerarDetalleCronograma_Regular", fECHA_INICIOParameter, fECHA_FINParameter, iD_CRONOGRAMAParameter);
        }
    
        public virtual ObjectResult<ObtenerCronogramaDetalle_Result> SP_ObtenerCronogramaDetalle(Nullable<int> iD_CRONOGRAMA, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_CRONOGRAMAParameter = iD_CRONOGRAMA.HasValue ?
                new ObjectParameter("ID_CRONOGRAMA", iD_CRONOGRAMA) :
                new ObjectParameter("ID_CRONOGRAMA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerCronogramaDetalle_Result>("SP_ObtenerCronogramaDetalle", iD_CRONOGRAMAParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<ObtenerRutaAdjunto_Result> SP_ObtenerRutaAdjunto(Nullable<int> iD_CRONOGRAMA_DETALLE, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_CRONOGRAMA_DETALLEParameter = iD_CRONOGRAMA_DETALLE.HasValue ?
                new ObjectParameter("ID_CRONOGRAMA_DETALLE", iD_CRONOGRAMA_DETALLE) :
                new ObjectParameter("ID_CRONOGRAMA_DETALLE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerRutaAdjunto_Result>("SP_ObtenerRutaAdjunto", iD_CRONOGRAMA_DETALLEParameter, outMensaje, outID);
        }
    
        public virtual int SPObtenerHorarioDetalle(Nullable<int> iD_PARALELO_MATERIA, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_PARALELO_MATERIAParameter = iD_PARALELO_MATERIA.HasValue ?
                new ObjectParameter("ID_PARALELO_MATERIA", iD_PARALELO_MATERIA) :
                new ObjectParameter("ID_PARALELO_MATERIA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SPObtenerHorarioDetalle", iD_PARALELO_MATERIAParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<ObtenerHorarioDetalle_Result> SP_ObtenerHorarioDetalle(Nullable<int> iD_PARALELO_MATERIA, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_PARALELO_MATERIAParameter = iD_PARALELO_MATERIA.HasValue ?
                new ObjectParameter("ID_PARALELO_MATERIA", iD_PARALELO_MATERIA) :
                new ObjectParameter("ID_PARALELO_MATERIA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerHorarioDetalle_Result>("SP_ObtenerHorarioDetalle", iD_PARALELO_MATERIAParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<ObtenerIntervaloPorSede_Result> SP_ObtenerIntervaloPorSede(Nullable<int> iD_SEDE, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_SEDEParameter = iD_SEDE.HasValue ?
                new ObjectParameter("ID_SEDE", iD_SEDE) :
                new ObjectParameter("ID_SEDE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerIntervaloPorSede_Result>("SP_ObtenerIntervaloPorSede", iD_SEDEParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<ObtenerIntervaloDetalle_Result> SP_ObtenerIntervaloDetalle(Nullable<int> iD_INTERVALO, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_INTERVALOParameter = iD_INTERVALO.HasValue ?
                new ObjectParameter("ID_INTERVALO", iD_INTERVALO) :
                new ObjectParameter("ID_INTERVALO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerIntervaloDetalle_Result>("SP_ObtenerIntervaloDetalle", iD_INTERVALOParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<ObtenerDiaLibreHorario_Result> SP_ObtenerDiaLibreHorario(Nullable<int> iD_INTERVALO_DETALLE, Nullable<int> iD_PARALELO_MATERIA, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_INTERVALO_DETALLEParameter = iD_INTERVALO_DETALLE.HasValue ?
                new ObjectParameter("ID_INTERVALO_DETALLE", iD_INTERVALO_DETALLE) :
                new ObjectParameter("ID_INTERVALO_DETALLE", typeof(int));
    
            var iD_PARALELO_MATERIAParameter = iD_PARALELO_MATERIA.HasValue ?
                new ObjectParameter("ID_PARALELO_MATERIA", iD_PARALELO_MATERIA) :
                new ObjectParameter("ID_PARALELO_MATERIA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerDiaLibreHorario_Result>("SP_ObtenerDiaLibreHorario", iD_INTERVALO_DETALLEParameter, iD_PARALELO_MATERIAParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<NotificadorEvento_Result> SP_NotificadorEvento(Nullable<int> iD_EVENTO_REGISTRO_DETALLE)
        {
            var iD_EVENTO_REGISTRO_DETALLEParameter = iD_EVENTO_REGISTRO_DETALLE.HasValue ?
                new ObjectParameter("ID_EVENTO_REGISTRO_DETALLE", iD_EVENTO_REGISTRO_DETALLE) :
                new ObjectParameter("ID_EVENTO_REGISTRO_DETALLE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NotificadorEvento_Result>("SP_NotificadorEvento", iD_EVENTO_REGISTRO_DETALLEParameter);
        }
    
        public virtual ObjectResult<DocenteHorarioTarea_Result> SP_DocenteHorarioTarea(string iD_DOCENTE, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_DOCENTEParameter = iD_DOCENTE != null ?
                new ObjectParameter("ID_DOCENTE", iD_DOCENTE) :
                new ObjectParameter("ID_DOCENTE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DocenteHorarioTarea_Result>("SP_DocenteHorarioTarea", iD_DOCENTEParameter, outMensaje, outID);
        }
    
        public virtual int SP_GenerarTareaEstudiante(Nullable<int> iD_TAREA)
        {
            var iD_TAREAParameter = iD_TAREA.HasValue ?
                new ObjectParameter("ID_TAREA", iD_TAREA) :
                new ObjectParameter("ID_TAREA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GenerarTareaEstudiante", iD_TAREAParameter);
        }
    
        public virtual ObjectResult<DocenteObtenerDetalleTarea_Result> SP_DocenteObtenerDetalleTarea(string iD_DOCENTE, Nullable<int> iD_SEDE, Nullable<int> iD_CARRERA, Nullable<int> iD_MATERIA, Nullable<int> iD_PARALELO, Nullable<int> iD_INTERVALO_DETALLE, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_DOCENTEParameter = iD_DOCENTE != null ?
                new ObjectParameter("ID_DOCENTE", iD_DOCENTE) :
                new ObjectParameter("ID_DOCENTE", typeof(string));
    
            var iD_SEDEParameter = iD_SEDE.HasValue ?
                new ObjectParameter("ID_SEDE", iD_SEDE) :
                new ObjectParameter("ID_SEDE", typeof(int));
    
            var iD_CARRERAParameter = iD_CARRERA.HasValue ?
                new ObjectParameter("ID_CARRERA", iD_CARRERA) :
                new ObjectParameter("ID_CARRERA", typeof(int));
    
            var iD_MATERIAParameter = iD_MATERIA.HasValue ?
                new ObjectParameter("ID_MATERIA", iD_MATERIA) :
                new ObjectParameter("ID_MATERIA", typeof(int));
    
            var iD_PARALELOParameter = iD_PARALELO.HasValue ?
                new ObjectParameter("ID_PARALELO", iD_PARALELO) :
                new ObjectParameter("ID_PARALELO", typeof(int));
    
            var iD_INTERVALO_DETALLEParameter = iD_INTERVALO_DETALLE.HasValue ?
                new ObjectParameter("ID_INTERVALO_DETALLE", iD_INTERVALO_DETALLE) :
                new ObjectParameter("ID_INTERVALO_DETALLE", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DocenteObtenerDetalleTarea_Result>("SP_DocenteObtenerDetalleTarea", iD_DOCENTEParameter, iD_SEDEParameter, iD_CARRERAParameter, iD_MATERIAParameter, iD_PARALELOParameter, iD_INTERVALO_DETALLEParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<DocenteCalificacionTarea_Result> SP_DocenteCalificacionTarea(Nullable<int> iD_TAREA, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_TAREAParameter = iD_TAREA.HasValue ?
                new ObjectParameter("ID_TAREA", iD_TAREA) :
                new ObjectParameter("ID_TAREA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DocenteCalificacionTarea_Result>("SP_DocenteCalificacionTarea", iD_TAREAParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<DocenteRepositorioAdjunto_Result> SP_DocenteRepositorioAdjunto(Nullable<int> iD_SEDE, Nullable<int> iD_CARRERA, Nullable<int> sEMANA_CRONOGRAMA, Nullable<int> iD_TIPO_INTERVALO, Nullable<int> iD_CARPETA, Nullable<int> iD_PERIODO, Nullable<int> iD_CRONOGRAMA, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_SEDEParameter = iD_SEDE.HasValue ?
                new ObjectParameter("ID_SEDE", iD_SEDE) :
                new ObjectParameter("ID_SEDE", typeof(int));
    
            var iD_CARRERAParameter = iD_CARRERA.HasValue ?
                new ObjectParameter("ID_CARRERA", iD_CARRERA) :
                new ObjectParameter("ID_CARRERA", typeof(int));
    
            var sEMANA_CRONOGRAMAParameter = sEMANA_CRONOGRAMA.HasValue ?
                new ObjectParameter("SEMANA_CRONOGRAMA", sEMANA_CRONOGRAMA) :
                new ObjectParameter("SEMANA_CRONOGRAMA", typeof(int));
    
            var iD_TIPO_INTERVALOParameter = iD_TIPO_INTERVALO.HasValue ?
                new ObjectParameter("ID_TIPO_INTERVALO", iD_TIPO_INTERVALO) :
                new ObjectParameter("ID_TIPO_INTERVALO", typeof(int));
    
            var iD_CARPETAParameter = iD_CARPETA.HasValue ?
                new ObjectParameter("ID_CARPETA", iD_CARPETA) :
                new ObjectParameter("ID_CARPETA", typeof(int));
    
            var iD_PERIODOParameter = iD_PERIODO.HasValue ?
                new ObjectParameter("ID_PERIODO", iD_PERIODO) :
                new ObjectParameter("ID_PERIODO", typeof(int));
    
            var iD_CRONOGRAMAParameter = iD_CRONOGRAMA.HasValue ?
                new ObjectParameter("ID_CRONOGRAMA", iD_CRONOGRAMA) :
                new ObjectParameter("ID_CRONOGRAMA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DocenteRepositorioAdjunto_Result>("SP_DocenteRepositorioAdjunto", iD_SEDEParameter, iD_CARRERAParameter, sEMANA_CRONOGRAMAParameter, iD_TIPO_INTERVALOParameter, iD_CARPETAParameter, iD_PERIODOParameter, iD_CRONOGRAMAParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<EstudianteRepositorioAdjunto_Result> SP_EstudianteRepositorioAdjunto(Nullable<int> iD_SEDE, Nullable<int> iD_CARRERA, Nullable<int> sEMANA_CRONOGRAMA, Nullable<int> iD_TIPO_INTERVALO, Nullable<int> iD_CARPETA, Nullable<int> iD_PARALELO, Nullable<int> iD_PERIODO, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_SEDEParameter = iD_SEDE.HasValue ?
                new ObjectParameter("ID_SEDE", iD_SEDE) :
                new ObjectParameter("ID_SEDE", typeof(int));
    
            var iD_CARRERAParameter = iD_CARRERA.HasValue ?
                new ObjectParameter("ID_CARRERA", iD_CARRERA) :
                new ObjectParameter("ID_CARRERA", typeof(int));
    
            var sEMANA_CRONOGRAMAParameter = sEMANA_CRONOGRAMA.HasValue ?
                new ObjectParameter("SEMANA_CRONOGRAMA", sEMANA_CRONOGRAMA) :
                new ObjectParameter("SEMANA_CRONOGRAMA", typeof(int));
    
            var iD_TIPO_INTERVALOParameter = iD_TIPO_INTERVALO.HasValue ?
                new ObjectParameter("ID_TIPO_INTERVALO", iD_TIPO_INTERVALO) :
                new ObjectParameter("ID_TIPO_INTERVALO", typeof(int));
    
            var iD_CARPETAParameter = iD_CARPETA.HasValue ?
                new ObjectParameter("ID_CARPETA", iD_CARPETA) :
                new ObjectParameter("ID_CARPETA", typeof(int));
    
            var iD_PARALELOParameter = iD_PARALELO.HasValue ?
                new ObjectParameter("ID_PARALELO", iD_PARALELO) :
                new ObjectParameter("ID_PARALELO", typeof(int));
    
            var iD_PERIODOParameter = iD_PERIODO.HasValue ?
                new ObjectParameter("ID_PERIODO", iD_PERIODO) :
                new ObjectParameter("ID_PERIODO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EstudianteRepositorioAdjunto_Result>("SP_EstudianteRepositorioAdjunto", iD_SEDEParameter, iD_CARRERAParameter, sEMANA_CRONOGRAMAParameter, iD_TIPO_INTERVALOParameter, iD_CARPETAParameter, iD_PARALELOParameter, iD_PERIODOParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<AdminRepositorioAdjunto_Result> SP_AdminRepositorioAdjunto(Nullable<int> sEMANA_CRONOGRAMA, Nullable<int> iD_CARPETA, Nullable<int> iD_CRONOGRAMA, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var sEMANA_CRONOGRAMAParameter = sEMANA_CRONOGRAMA.HasValue ?
                new ObjectParameter("SEMANA_CRONOGRAMA", sEMANA_CRONOGRAMA) :
                new ObjectParameter("SEMANA_CRONOGRAMA", typeof(int));
    
            var iD_CARPETAParameter = iD_CARPETA.HasValue ?
                new ObjectParameter("ID_CARPETA", iD_CARPETA) :
                new ObjectParameter("ID_CARPETA", typeof(int));
    
            var iD_CRONOGRAMAParameter = iD_CRONOGRAMA.HasValue ?
                new ObjectParameter("ID_CRONOGRAMA", iD_CRONOGRAMA) :
                new ObjectParameter("ID_CRONOGRAMA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AdminRepositorioAdjunto_Result>("SP_AdminRepositorioAdjunto", sEMANA_CRONOGRAMAParameter, iD_CARPETAParameter, iD_CRONOGRAMAParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<AdminRepositorioCarpeta_Result> SP_AdminRepositorioCarpeta(Nullable<int> sEMANA_CRONOGRAMA, Nullable<int> iD_CRONOGRAMA, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var sEMANA_CRONOGRAMAParameter = sEMANA_CRONOGRAMA.HasValue ?
                new ObjectParameter("SEMANA_CRONOGRAMA", sEMANA_CRONOGRAMA) :
                new ObjectParameter("SEMANA_CRONOGRAMA", typeof(int));
    
            var iD_CRONOGRAMAParameter = iD_CRONOGRAMA.HasValue ?
                new ObjectParameter("ID_CRONOGRAMA", iD_CRONOGRAMA) :
                new ObjectParameter("ID_CRONOGRAMA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AdminRepositorioCarpeta_Result>("SP_AdminRepositorioCarpeta", sEMANA_CRONOGRAMAParameter, iD_CRONOGRAMAParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<AdminRepositorioSemana_Result> SP_AdminRepositorioSemana(Nullable<int> iD_CRONOGRAMA, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_CRONOGRAMAParameter = iD_CRONOGRAMA.HasValue ?
                new ObjectParameter("ID_CRONOGRAMA", iD_CRONOGRAMA) :
                new ObjectParameter("ID_CRONOGRAMA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<AdminRepositorioSemana_Result>("SP_AdminRepositorioSemana", iD_CRONOGRAMAParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<EstudianteObtenerCarrera_Result> SP_EstudianteObtenerCarrera(string iD_ESTUDIANTE, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_ESTUDIANTEParameter = iD_ESTUDIANTE != null ?
                new ObjectParameter("ID_ESTUDIANTE", iD_ESTUDIANTE) :
                new ObjectParameter("ID_ESTUDIANTE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EstudianteObtenerCarrera_Result>("SP_EstudianteObtenerCarrera", iD_ESTUDIANTEParameter, outMensaje, outID);
        }
    
        public virtual int SP_EliminarTareas(Nullable<int> iD_TAREA)
        {
            var iD_TAREAParameter = iD_TAREA.HasValue ?
                new ObjectParameter("ID_TAREA", iD_TAREA) :
                new ObjectParameter("ID_TAREA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_EliminarTareas", iD_TAREAParameter);
        }
    
        public virtual ObjectResult<EstudianteObtenerTareasDetalle_Result> SP_EstudianteObtenerTareasDetalle(string iD_ESTUDIANTE, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_ESTUDIANTEParameter = iD_ESTUDIANTE != null ?
                new ObjectParameter("ID_ESTUDIANTE", iD_ESTUDIANTE) :
                new ObjectParameter("ID_ESTUDIANTE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EstudianteObtenerTareasDetalle_Result>("SP_EstudianteObtenerTareasDetalle", iD_ESTUDIANTEParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<DocenteHorarioMateria_Result> SP_DocenteHorarioMateria(string iD_DOCENTE, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_DOCENTEParameter = iD_DOCENTE != null ?
                new ObjectParameter("ID_DOCENTE", iD_DOCENTE) :
                new ObjectParameter("ID_DOCENTE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DocenteHorarioMateria_Result>("SP_DocenteHorarioMateria", iD_DOCENTEParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<ObtenerNota_Result> SP_ObtenerNota(ObjectParameter outMensaje, ObjectParameter outID)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerNota_Result>("SP_ObtenerNota", outMensaje, outID);
        }
    
        public virtual ObjectResult<ObtenerNotaDetalle_Result> SP_ObtenerNotaDetalle(Nullable<int> iD_NOTA, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_NOTAParameter = iD_NOTA.HasValue ?
                new ObjectParameter("ID_NOTA", iD_NOTA) :
                new ObjectParameter("ID_NOTA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ObtenerNotaDetalle_Result>("SP_ObtenerNotaDetalle", iD_NOTAParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<EstudianteObtenerCarreraReporteDocente_Result> SP_EstudianteObtenerCarreraReporteDocente(string iD_ESTUDIANTE, Nullable<int> iD_PERIODO, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_ESTUDIANTEParameter = iD_ESTUDIANTE != null ?
                new ObjectParameter("ID_ESTUDIANTE", iD_ESTUDIANTE) :
                new ObjectParameter("ID_ESTUDIANTE", typeof(string));
    
            var iD_PERIODOParameter = iD_PERIODO.HasValue ?
                new ObjectParameter("ID_PERIODO", iD_PERIODO) :
                new ObjectParameter("ID_PERIODO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EstudianteObtenerCarreraReporteDocente_Result>("SP_EstudianteObtenerCarreraReporteDocente", iD_ESTUDIANTEParameter, iD_PERIODOParameter, outMensaje, outID);
        }
    
        public virtual ObjectResult<DocenteObtenerNotas_Result> SP_DocenteObtenerNotas(string iD_DOCENTE, Nullable<int> iD_PERIODO, ObjectParameter outMensaje, ObjectParameter outID)
        {
            var iD_DOCENTEParameter = iD_DOCENTE != null ?
                new ObjectParameter("ID_DOCENTE", iD_DOCENTE) :
                new ObjectParameter("ID_DOCENTE", typeof(string));
    
            var iD_PERIODOParameter = iD_PERIODO.HasValue ?
                new ObjectParameter("ID_PERIODO", iD_PERIODO) :
                new ObjectParameter("ID_PERIODO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DocenteObtenerNotas_Result>("SP_DocenteObtenerNotas", iD_DOCENTEParameter, iD_PERIODOParameter, outMensaje, outID);
        }
    }
}
