//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAS_ESTUDIANTE_TAREA
    {
        public int ID_ESTUDIANTE_TAREA { get; set; }
        public Nullable<int> ID_TAREA { get; set; }
        public string ID_ESTUDIANTE { get; set; }
        public string ADJUNTO_TAREA { get; set; }
        public Nullable<System.DateTime> FECHA_TAREA { get; set; }
        public Nullable<decimal> NOTA_TAREA { get; set; }
        public string ADJUNTO_NOMBRE { get; set; }
        public string OBSERVACION_TAREA { get; set; }
    }
}
