//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAS_CARRERA_REQUISITOS
    {
        public int ID_CARRERA_REQUISITOS { get; set; }
        public Nullable<int> ID_CARRERA_PADRE { get; set; }
        public Nullable<int> ID_CARRERA_HIJO { get; set; }
    }
}
