//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAS_ROL_MENU
    {
        public int ID_ROL_MENU { get; set; }
        public Nullable<int> ID_ROL { get; set; }
        public Nullable<int> ID_MENU { get; set; }
    }
}
