//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAS_EVENTO_REGISTRO
    {
        public string EVENTO_REGISTRO_CORREO { get; set; }
        public string EVENTO_REGISTRO_NOMBRES { get; set; }
        public string EVENTO_REGISTRO_APELLIDOS { get; set; }
        public string EVENTO_REGISTRO_MOVIL { get; set; }
    }
}
