//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAS_EVENTO_REGISTRO_DETALLE
    {
        public int ID_EVENTO_REGISTRO_DETALLE { get; set; }
        public string EVENTO_REGISTRO_CORREO { get; set; }
        public Nullable<int> ID_EVENTO { get; set; }
        public string IMAGE_CODE_BAR { get; set; }
        public string CODE_BAR { get; set; }
        public Nullable<bool> ESTADO { get; set; }
    }
}
