//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAS_TAREA_ADJUNTO
    {
        public int ID_TAREA_ADJUNTO { get; set; }
        public Nullable<int> ID_TAREA { get; set; }
        public string PATH_ADJUNTO { get; set; }
        public string NOMBRE_ADJUNTO { get; set; }
    }
}
