//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAS_INSCRIPCION_DETALLE_CARRERA
    {
        public int ID_INSCRIP_DETALLE_CARRERA { get; set; }
        public string ID_INSCRIP { get; set; }
        public Nullable<int> ID_SEDE { get; set; }
        public Nullable<int> ID_CARRERA { get; set; }
        public Nullable<int> ID_INTERVALO { get; set; }
        public Nullable<int> ID_INTERVALO_DETALLE { get; set; }
        public Nullable<int> ID_TIPO_PAGO { get; set; }
        public string NUMERO_FACTURA { get; set; }
        public Nullable<int> ID_ESTATUS { get; set; }
        public Nullable<int> ID_PARALELO { get; set; }
        public Nullable<int> ID_PERIODO { get; set; }
    }
}
