//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAS_CRONOGRAMA_DETALLE
    {
        public int ID_CRONOGRAMA_DETALLE { get; set; }
        public Nullable<int> ID_CRONOGRAMA { get; set; }
        public Nullable<int> SEMANA_CRONOGRAMA { get; set; }
        public Nullable<System.DateTime> FECHA_CRONOGRAMA { get; set; }
        public string TEMA { get; set; }
        public string TEMATICA { get; set; }
        public string REQUERIMIENTO { get; set; }
        public Nullable<bool> FERIADO { get; set; }
    }
}
