//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAS_ESTUDIANTE
    {
        public string ID_ESTUDIANTE { get; set; }
        public string APELLIDO_PATERNO_ESTUDIANTE { get; set; }
        public string APELLIDO_MATERNO_ESTUDIANTE { get; set; }
        public string PRIMER_NOMBRE_ESTUDIANTE { get; set; }
        public string SEGUNDO_NOMBRE_ESTUDIANTE { get; set; }
        public Nullable<System.DateTime> FECHA_NACIMIENTO_ESTUDIANTE { get; set; }
        public Nullable<int> ID_ESTADO_CIVIL { get; set; }
        public Nullable<int> ID_PROVINCIA { get; set; }
        public string DIRECCION { get; set; }
        public string TELEF_ESTUDIANTE { get; set; }
        public string CEL_ESTUDIANTE { get; set; }
        public string IMG_ESTUDIANTE { get; set; }
        public string CORREO_ESTUDIANTE { get; set; }
        public Nullable<System.DateTime> FECHA_INGRESO_ESTUDIANTE { get; set; }
    }
}
