//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAS_DOCENTE_ASISTENCIA
    {
        public int ID_DOCENTE_ASISTENCIA { get; set; }
        public int ID_HORARIO_DETALLE { get; set; }
        public string ID_DOCENTE { get; set; }
        public System.DateTime FECHA_ASISTENCIA { get; set; }
        public System.TimeSpan HORA_ASISTENCIA { get; set; }
        public string OBSERVACION_ASISTENCIA { get; set; }
        public System.DateTime FECHA_REGISTRO { get; set; }
        public Nullable<int> ESTADO_ASISTENCIA { get; set; }
        public Nullable<int> ID_PERIODO { get; set; }
    }
}
