//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAS_AUDITORIA
    {
        public int AUD_ID { get; set; }
        public string USR_ID { get; set; }
        public string AUD_SESSION { get; set; }
        public Nullable<System.DateTime> AUD_FECHA_HORA { get; set; }
        public string AUD_ACCION { get; set; }
        public string AUD_DATA { get; set; }
        public string USR_CODIGO { get; set; }
    }
}
