//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Data
{
    using System;
    
    public partial class NotificadorEnviaClave_Result
    {
        public int MSG_ID { get; set; }
        public Nullable<int> MSG_CODIGO { get; set; }
        public Nullable<int> BDJ_ID { get; set; }
        public string MSG_DESTINATARIO { get; set; }
        public string MSG_REMITENTE { get; set; }
        public string MSG_ASUNTO { get; set; }
        public string MSG_TEXTO { get; set; }
        public string MSG_FORMATO { get; set; }
        public Nullable<System.DateTime> MSG_FECHA_CREACION { get; set; }
        public Nullable<System.DateTime> MSG_FECHA_RECIBIDO { get; set; }
        public Nullable<System.DateTime> MSG_FECHA_ENVIADO { get; set; }
        public Nullable<System.DateTime> MSG_FECHA_CONFIRMADO { get; set; }
        public Nullable<int> MSG_CANAL { get; set; }
        public string USR_CODIGO { get; set; }
        public Nullable<int> COD_ACCESO { get; set; }
    }
}
