//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAS_CRONOGRAMA
    {
        public int ID_CRONOGRAMA { get; set; }
        public Nullable<int> ID_CARRERA { get; set; }
        public Nullable<int> ID_SEDE { get; set; }
        public Nullable<int> ID_PERIODO { get; set; }
        public Nullable<int> ID_TIPO_INTERVALO { get; set; }
        public string DESCRIPCION_CRONOGRAMA { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO { get; set; }
        public Nullable<System.DateTime> FECHA_FIN { get; set; }
        public Nullable<int> ID_PARALELO { get; set; }
    }
}
