//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Data
{
    using System;
    
    public partial class ObtenerIntervaloSedeCarrera_Result
    {
        public int ID_INTERVALO { get; set; }
        public Nullable<int> ID_TIPO_INTERVALO { get; set; }
        public Nullable<int> ID_HORARIO_TIPO { get; set; }
        public Nullable<int> ID_SEDE { get; set; }
        public string DESCRIPCION_INTERVALO { get; set; }
    }
}
