//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAS_NOTIFICACIONES
    {
        public int ID_NOTIFICACION { get; set; }
        public string ID_USUARIO { get; set; }
        public string TXT_NOTIFICACION { get; set; }
        public Nullable<long> ESTADO_NOTIFICACION { get; set; }
        public Nullable<System.DateTime> FECHA_NOTIFICACION { get; set; }
        public string ID_USUARIO_REMITENTE { get; set; }
        public string ASUNTO_NOTIFICACION { get; set; }
        public Nullable<int> ID_PERIODO { get; set; }
        public Nullable<int> PRIORIDAD_NOTIFICACION { get; set; }
    }
}
